twopages3/config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'about', to: 'home#about'
  get 'contact', to: 'home#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

twopages3/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

twopages3/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

twopages3/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
     #render text: "Hello world"
  end

  def about
  end

  def contact
  end
end

twopages3/app/helpers/application_helper.rb
module ApplicationHelper
end

twopages3/app/helpers/home_helper.rb
module HomeHelper
end

twopages3/app/views/home/_menu.html.erb
<div>
<%= link_to 'Home', root_url %>
<%= link_to 'About', about_url %>
<%= link_to 'Contact', contact_url %>
<%= link_to 'Foo', page_path('foo') %>
</div>

twopages3/app/views/home/about.html.erb
<% content_for :title, 'About page' %>

<% content_for :sidebar do %>
  <%= render 'menu' %>
  About......
<% end %>

<h1>About</h1>

twopages3/app/views/home/contact.html.erb
<% content_for :title, 'Contact page' %>

<% content_for :sidebar do %>
  <%= render 'menu' %>
  Contact......
<% end %>

<h1>Contact</h1>

twopages3/app/views/home/index.html.erb
<h1>Home#index</h1>
<%= render 'menu' %>

twopages3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='sidebar'>
      <%= yield :sidebar %>
    </div>
    <div>
      <%= yield %>
    </div>
  </body>
</html>

twopages3/app/views/pages/foo.html.erb
<% content_for :title, 'Foo high voltage page' %>

<% content_for :sidebar do %>
  <%= render 'home/menu' %>
  Foo......
<% end %>

<h1>This is foo</h1>